### PR TITLE
Fix bootstrap exec

### PR DESCRIPTION
**Pull request by dmoverton**

### CODE REVIEW

**Comment by koterpillar** [comment]
What error, and in which configuration, are you getting without that path element?

**Comment by koterpillar** [comment]
I thought https://github.com/seek-oss/serverless-haskell/blob/4a21a17fb37017d73a21dabf8e6c42e3946c0230/index.ts#L338 and https://github.com/seek-oss/serverless-haskell/blob/4a21a17fb37017d73a21dabf8e6c42e3946c0230/index.ts#L343 will already add `./`.

**Comment by dmoverton** [comment]
The error message was ```/var/task/bootstrap: line 2: exec: autoinc-uap-expirer-exe: not found```

I didn't realise at the time that you were rewriting the handler in the plugin to add the `targetDirectory`. Our deployment doesn't use that, so I guess the correct fix is to add `./` to the handler in our custom Cloudformation.

**Comment by dmoverton** [comment]
I'll test that now. If it works I'll close this PR.

**Comment by dmoverton** [comment]
I've tested adding `./` to the `Handler` in our custom Cloudformation and it works. So closing this PR.

**Pull request closed without merging**
